# Generated by Django 4.1.5 on 2023-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gradinita_app",
            "0002_alter_kids_age_alter_kids_group_alter_kids_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="full_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="kids",
            name="group",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="kids",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="kids",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
