# Generated by Django 4.1.5 on 2023-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0003_alter_kids_full_name_alter_kids_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="age",
            field=models.CharField(max_length=10),
        ),
    ]
