# Generated by Django 4.1.5 on 2023-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0004_alter_kids_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
