# Generated by Django 4.1.5 on 2023-03-12 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0005_alter_kids_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
