# Generated by Django 4.1.5 on 2023-03-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0006_alter_kids_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="gradinita_app.profile",
            ),
        ),
    ]
