# Generated by Django 4.1.5 on 2023-03-12 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0007_alter_kids_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="motivari_elev",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("numar", models.IntegerField()),
                ("data", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradinita_app.kids",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="absente_elev",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("numar", models.IntegerField()),
                ("data", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradinita_app.kids",
                    ),
                ),
            ],
        ),
    ]
