# Generated by Django 4.1.5 on 2023-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0008_motivari_elev_absente_elev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absente_elev",
            name="data",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="motivari_elev",
            name="data",
            field=models.DateTimeField(blank=True),
        ),
    ]
