# Generated by Django 4.1.5 on 2023-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0009_alter_absente_elev_data_alter_motivari_elev_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absente_elev",
            name="data",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="motivari_elev",
            name="data",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
