# Generated by Django 4.1.5 on 2023-03-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0011_alter_absente_elev_owner_alter_motivari_elev_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absente_elev",
            name="data",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="motivari_elev",
            name="data",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
