# Generated by Django 4.1.5 on 2023-03-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gradinita_app",
            "0013_alter_absente_elev_data_alter_absente_elev_numar_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="absente_elev",
            name="data",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
