# Generated by Django 4.1.5 on 2023-03-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0014_alter_absente_elev_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absente_elev",
            name="numar",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="kids",
            name="absente",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kids",
            name="motivari",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="motivari_elev",
            name="numar",
            field=models.IntegerField(),
        ),
    ]
