# Generated by Django 4.1.5 on 2023-03-27 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gradinita_app", "0015_alter_absente_elev_numar_alter_kids_absente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
