# Generated by Django 4.1.5 on 2023-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0020_alter_absente_elev_id_alter_kids_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
