# Generated by Django 4.1.5 on 2023-03-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0023_alter_absente_elev_id_alter_kids_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gradinita_app.profile",
            ),
        ),
    ]
