# Generated by Django 4.1.5 on 2023-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0024_alter_kids_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="kids",
            name="key",
            field=models.CharField(
                blank=True, default="0", max_length=10000, null=True
            ),
        ),
    ]
