# Generated by Django 4.1.5 on 2023-03-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0025_kids_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kids",
            name="key",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
