# Generated by Django 4.1.5 on 2023-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradinita_app", "0026_alter_kids_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, default="none", max_length=15, null=True
            ),
        ),
    ]
